
repositories {
    mavenLocal()
    maven {
        url = uri('https://www.hec.usace.army.mil/nexus/repository/maven-public')
    }

    mavenCentral().content {
        // The jai_core on maven central has the pom but not the jar.
        excludeModule("javax.media", "jai_core")
    }

    maven {
        url = uri('https://repo.maven.apache.org/maven2')
    }
    gradlePluginPortal()
}


configurations.all {
    exclude group: "org.python", module: "jython-standalone"

    resolutionStrategy {
        // javalin 4.6.8 pulls in the vulnerable kotlin-stdlib 1.5.32 
        // Force a patched version; javalin can't be bumped past 4.x while we target Java 11.
        force "org.jetbrains.kotlin:kotlin-stdlib:1.9.25"
        force "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.25"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.25"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.25"
    }
}
