export CATALINA_OPTS="$CATALINA_OPTS -Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource"

export CDA_JDBC_DRIVER=$RADAR_JDBC_DRIVER
export CDA_JDBC_URL=$RADAR_JDBC_URL
export CDA_JDBC_USERNAME=$RADAR_JDBC_USERNAME
export CDA_JDBC_PASSWORD=$RADAR_JDBC_PASSWORD
export CDA_POOL_INIT_SIZE=$RADAR_POOL_INIT_SIZE
export CDA_POOL_MAX_ACTIVE=$RADAR_POOL_MAX_ACTIVE
export CDA_POOL_MAX_IDLE=$RADAR_POOL_MAX_IDLE
export CDA_POOL_MIN_IDLE=$RADAR_POOL_MIN_IDLE
