name: 'Clean Disk Space'
description: Frees up disk of stuff we don't use
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Clean up disk space, so we don't run out.
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    