services:
  cda-etl:
    build: .
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      -SOURCE_CDA_URL:
      -SOURCE_CDA_API_KEY:
      -DEST_CDA_URL:
      -DEST_CDA_API_KEY:
      -START_TIME:
      -END_TIME:
      -LOOKBACK:
