import org.openapitools.generator.gradle.plugin.tasks.GenerateTask
import org.openapitools.generator.gradle.plugin.tasks.ValidateTask

plugins {
    id 'java'
    id 'cda.deps-conventions'
    id 'cda.java-conventions'
    id 'java-library'
    id 'com.github.node-gradle.node' version '7.1.0'
    id "org.openapi.generator" version "7.15.0"
}
if (JavaVersion.current() >= JavaVersion.VERSION_11) {

    tasks.register('validateOpenApiSpec', ValidateTask) {
        dependsOn(":cwms-data-api:executeOpenAPIConversion")
        inputSpec.set("$rootDir/cwms-data-api/build/openapi.json")
    }

    tasks.register('generateOpenApiDoc', GenerateTask) {
        dependsOn(":cwms-data-api:executeOpenAPIConversion")
        validateSpec = true
        inputSpec = "$rootDir/cwms-data-api/build/openapi.json"
        outputDir = "$buildDir/generated/openApi"
        configFile = "$rootDir/cda-client/openapi.config.json"
        generatorName = "typescript-fetch"
        globalProperties.set([
                modelDocs             : "true",
                modelTests            : "false",
                apiDocs               : "true",
                apiTests              : "false",
                enabledPostProcessFile: "false"
        ])
        ignoreFileOverride = "$rootDir/cda-client/.openapi-generator-ignore"
    }

    tasks.register('verifySpec', NpxTask) {
        group 'documentation'
        dependsOn npmInstall
        dependsOn(generateOpenApiDoc)
        dependsOn(validateOpenApiSpec)
        command = "npm"
        args = ["run", "build"]
        inputs.files('package.json', 'package-lock.json')
        inputs.dir(fileTree("node_modules").exclude(".cache"))
        outputs.dir('dist')
    }
}

dependencies {
    implementation(project(":cwms-data-api"))
}

tasks.register('cleanGeneration', Delete) {
    delete project.layout.projectDirectory.dir('build')
    delete project.layout.projectDirectory.dir('dist')
    delete project.layout.projectDirectory.dir('node_modules')
}

clean.dependsOn cleanGeneration