---
name: Build And Test CWMS Data API
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: [11]
        schema:
          - env: latest
            image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:latest-dev"
          - env: release
            image: "ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/database-ready-ora-23.5:25.07.01"
    name: build and test (jdk ${{matrix.jdk}}, schema ${{matrix.schema.env}})
    runs-on: ubuntu-latest
    outputs:
      thewar: ${{steps.thebuild.outputs.WARFILE}}
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: setup java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{matrix.jdk}}
          cache: 'gradle'
      - name: build and test
        id: thebuild
        run: ./gradlew build --info --init-script init.gradle
      - name: integration tests
        run: ./gradlew integrationtest --info --init-script init.gradle -PCDA.oracle.database.image=${{matrix.schema.image}}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          annotate_only: true
          include_passed: true
          report_paths: '**/TEST-*.xml'
  open-api-static-analysis:
    name: OpenApi Static Analysis Tests
    runs-on: ubuntu-latest
    env:
      OPEN_API_TEST: "true"
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: setup java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: build and test
        id: thebuild
        run: ./gradlew :cwms-data-api:test --tests "cwms.cda.api.OpenApiDocTest" --info --init-script init.gradle
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          annotate_only: true
          include_passed: true
          report_paths: '**/TEST-*.xml'
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: Build docker image
        run: docker build -t cda:build-latest .
  build-schema-migration-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: Build Migration image
        uses: ./.github/actions/database-migration-image
        with:
          base-image: ghcr.io/hydrologicengineeringcenter/cwms-database/cwms/schema_installer
          # TODO get current target image from build information
          tag: latest

      # No uploads, we're just verifying that nothing broke the docker image.
