name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment (test/prod) to deploy to"
        required: true
        default: 'Test'
        type: environment
      activate:
        description: "If true, will also set to current running. Otherwise just verifies we can push the image"
        required: true
        default: false
        type: boolean


jobs:
  # Deploy CDA nightly. Keeps everyone on their toes with new updates and keeps the containers
  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Deploy
        uses: ./.github/workflows/deploy.yml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{github.ref_name}}
          region: ${{env.REGION}}
          iam_role: ${{env.DEPLOY_ROLE}}
          activation_tag: ${{env.ACTIVATION_TAG}}
          activate: ${{inputs.activate}}
