name: Nightly Releases - Schedule
on:
  schedule:
    - cron: "3 0 * * *"

jobs:
  develop:
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      registry: ${{ secrets.HEC_PUB_REGISTRY}}
      registry_user: ${{ secrets.ALT_REG_USER }}
      registry_password: ${{ secrets.ALT_REG_PASSWORD }}
    with:
      branch: "develop"
      nightly: true
  # Deploy CDA nightly. Keeps everyone on their toes with new updates and keeps the containers 
  # Updated
  deploy-develop:
    permissions:
      id-token: write
      contents: read
    needs: develop
    uses: ./.github/workflows/deploy.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      api_image: ${{develop.outputs.image_tag}}
      region: us-gov-west-1
      iam_role: arn:aws-us-gov:iam::718787032875:role/github-actions-ecr-cwms-data-api
